name: Build PrestaShop Module on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build PrestaShop Module
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Module
        run: |
          mkdir -p dist
          zip -r dist/prestashop-module-$GITHUB_REF_NAME.zip . -x '*.git*' -x 'dist/*'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/prestashop-module-$GITHUB_REF_NAME.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

